language: python
python:
  - 2.7

# command to install dependencies
install: pip install -r requirements.txt
# enforce some code style standards
before_script: 
  - pip install flake8 --use-mirrors
  - flake8 --ignore=E731,E226 .
# command to run tests
script: nosetests
